name: CI

on:
  push:
    branches:
      - main
      - ci_testing_*
  pull_request:

jobs:
  lint-and-fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Install python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Setup dependencies
        run: |
          pip install -U mypy black
          pip install -r requirements.txt
          mypy --install-types

      - name: Format check
        run: black src --check

      - name: MyPy linting
        run: mypy src
